import { Background } from '@next-app/components/assets/background'
import './globals.css'
import { Outfit } from 'next/font/google'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: '#Bora Codar 27',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} w-screen h-screen flex justify-center items-center`}>
        <Background />
        {children}
      </body>
    </html>
  )
}
